### ISSUE TITLE
连接自己搭建的节点没法获取部署的合约名，但是通过infura却可以，请问这个怎么解决？

### ISSUE THREAD

**Issue by shippomx** [finejian/go-connect-eth-contract#1]
nodeAddr := "http://192.168.3.198:8545"
    // nodeAddr := "https://mainnet.infura.io/fGl7FoHFjbofgA2BSEGK"
    conn, err := ethclient.Dial(nodeAddr)
	if err != nil {
        log.Fatalf("Failed to connect to the Ethereum client: %v", err)
    }
    myToken, err := token.NewToken(common.HexToAddress(contractAddress), conn)
    if err != nil {
        log.Fatalf("Failed to instantiate a Token contract: %v", err)
    }

    contractName, err := myToken.Name(nil)
    if err != nil {
        log.Fatalf("query name err:%v", err)
    }

急求解决方式啊，是我的启动geth方式不对吗？

**Comment by shippomx** [comment]
geth --rpc --rpcport=8545 --ws --wsport=8546 --rpccorsdomain="*" --datadir /home/soha/.ethash --rpcaddr 0.0.0.0 --wsaddr 0.0.0.0

**Comment by finejian** [comment]
本地启动的开发结点，需要开启挖矿才可以部署合约，开启方式是 geth启动命令添加 --dev --dev.period 1
